"""fix resume active version foreign key

Revision ID: 305d0ad68ae7
Revises: f44f0c711117
Create Date: 2026-09-12 18:10:08.042707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305d0ad68ae7'
down_revision: Union[str, Sequence[str], None] = 'f44f0c711117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'resumes', 'resume_versions', ['active_version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    # ### end Alembic commands ###
