"""remove professional email verification

Revision ID: 560de187fff3
Revises: e1680932171d
Create Date: 2026-09-13 22:42:57.248907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '560de187fff3'
down_revision: Union[str, Sequence[str], None] = 'e1680932171d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_connections_user_id'), table_name='email_connections')
    op.create_index(op.f('ix_email_connections_user_id'), 'email_connections', ['user_id'], unique=True)
    op.drop_column('profiles', 'professional_email_verification_token_hash')
    op.drop_column('profiles', 'professional_email_verified_at')
    op.drop_column('profiles', 'professional_email_verification_expires_at')
    op.alter_column('resumes', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('resumes', 's3_key',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('resumes', 'object_url',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    op.alter_column('resumes', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('resumes', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.alter_column('resumes', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('resumes', 'content_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('resumes', 'object_url',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    op.alter_column('resumes', 's3_key',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('resumes', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('profiles', sa.Column('professional_email_verification_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('professional_email_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('professional_email_verification_token_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_email_connections_user_id'), table_name='email_connections')
    op.create_index(op.f('ix_email_connections_user_id'), 'email_connections', ['user_id'], unique=False)
    # ### end Alembic commands ###
