"""add professional email verification

Revision ID: f44f0c711117
Revises: 80a762ed5227
Create Date: 2026-09-12 10:26:14.758137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44f0c711117'
down_revision: Union[str, Sequence[str], None] = '80a762ed5227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('professional_email', sa.String(length=320), nullable=True))
    op.add_column('profiles', sa.Column('professional_email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('professional_email_verification_token_hash', sa.String(length=128), nullable=True))
    op.add_column('profiles', sa.Column('professional_email_verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'professional_email_verification_expires_at')
    op.drop_column('profiles', 'professional_email_verification_token_hash')
    op.drop_column('profiles', 'professional_email_verified_at')
    op.drop_column('profiles', 'professional_email')
    # ### end Alembic commands ###
