apiVersion: v1
kind: Service
metadata:
  name: core-backend
  namespace: careerforge

spec:
  type: ClusterIP

  selector:
    app: core-backend

  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP