apiVersion: v1
kind: ConfigMap
metadata:
  name: agentic-service-config
  namespace: careerforge
data:
  ENVIRONMENT: "production"

  AWS_REGION: "ap-south-1"

  PORT: "8001"

  # Internal communication with Core Backend
  CORE_BACKEND_URL: "http://core-backend:8000"

  # Vector / embedding configuration
  EMBEDDING_PROVIDER: "bedrock"
  EMBEDDING_MODEL_ID: "amazon.titan-embed-text-v2:0"

  # LLM provider
  LLM_PROVIDER: "gemini"

  # These are configuration values, not secrets.
  # Actual API keys go in Secret.