apiVersion: v1
kind: Service
metadata:
  name: agentic-service
  namespace: careerforge

spec:
  type: ClusterIP

  selector:
    app: agentic-service

  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP